version: 5.7.2.{build}
os: Visual Studio 2015
environment:
  matrix:
  - {}
build_script:
- cmd: >-
    mkdir build
    cd build
    cmake c:\Projects\libwb -G "Visual Studio 14"
    cmake --build . --config Debug
